print("---------------------------------")
print("Xin chao! Day la ung dung Python.")
print("Duoc chay boi Jenkins CI.")
print("Duoc sửa bởi giangltapple.")
print("---------------------------------")
